services:
  server:
    container_name: bark-gpt-api
    # image: vvasylkovskyi1/vvasylkovskyi-bark-gpt-api:c60c211061a93c8b70935fa3576a297eaa5ba1d1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=my-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    ports:
      - "9999:9999"
    extra_hosts:
      - "host.docker.internal:host-gateway"